#!/usr/bin/env python3
"""Regenerates manifest_fixture.inc from the published OpenStore info.json.

The fixture carries the raw manifest bytes, the canonical signature payload
computed with the release tool's rules, and the values the host test expects
the C++ parser to extract. Run it whenever update/info.json changes:

    python test/host/gen_fixture.py [path/to/info.json]
"""

from __future__ import annotations

import io
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
DEFAULT_INFO = HERE.parents[2] / "OpenStore" / "update" / "info.json"
SIGNED_FIELDS = ("schema", "product", "channel", "target", "partitionScheme", "name",
                 "version", "versionCode", "minUpdaterVersionCode", "releaseType",
                 "description", "publishedAt", "firmware", "size", "sha256", "keyId")


def canonical_payload(info: dict) -> bytes:
    out = bytearray(b"OPENOS-OTA-V1\n")
    for field in SIGNED_FIELDS:
        encoded = str(info[field]).encode("utf-8")
        out += field.encode() + b":" + str(len(encoded)).encode() + b":" + encoded + b"\n"
    return bytes(out)


def c_literal(data: bytes) -> str:
    parts, current = [], ""
    for byte in data:
        if byte == 0x0A:
            current += "\\n"
            parts.append('"' + current + '"')
            current = ""
        elif byte == 0x22:
            current += '\\"'
        elif byte == 0x5C:
            current += "\\\\"
        elif 0x20 <= byte < 0x7F:
            current += chr(byte)
        else:
            current += '\\x%02x""' % byte  # close/reopen so a hex digit cannot follow
    if current:
        parts.append('"' + current + '"')
    return "\n    ".join(parts)


def main() -> None:
    info_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_INFO
    raw = info_path.read_bytes()
    info = json.loads(raw)
    lines = [
        "// Generated by gen_fixture.py from %s -- do not edit." % info_path.name,
        "",
        "// info.json exactly as published",
        "static const char* INFO_JSON =\n    " + c_literal(raw) + ";",
        "",
        "// canonical signature payload computed by the Python release tool rules",
        "static const char* INFO_CANONICAL =\n    " + c_literal(canonical_payload(info)) + ";",
        "",
        "// values the parser must extract from INFO_JSON",
        'static const char* INFO_EXPECTED_NAME = "%s";' % info["name"],
        'static const char* INFO_EXPECTED_FIRMWARE = "%s";' % info["firmware"],
        'static const char* INFO_EXPECTED_KEY_ID = "%s";' % info["keyId"],
        'static const char* INFO_EXPECTED_TARGET = "%s";' % info["target"],
        'static const char* INFO_EXPECTED_PARTITION = "%s";' % info["partitionScheme"],
        "static const unsigned INFO_EXPECTED_VERSION_CODE = %du;" % info["versionCode"],
        "static const unsigned INFO_EXPECTED_SIZE = %du;" % info["size"],
        "",
    ]
    (HERE / "manifest_fixture.inc").write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print("wrote manifest_fixture.inc for", info["name"])


if __name__ == "__main__":
    main()
